// Package arch_test enforces architectural invariants that no single package
// can guard on its own. The invariant here is the config boundary:
//
//	ALL environment-variable reading lives in exactly one place —
//	internal/config. Deeper layers receive typed configuration by injection.
//
// Why this matters: the operator-facing configuration reference
// (docs-site/src/data/generated/config.json) is generated by cmd/docsgen from
// internal/config/config.go alone. If any other shipped package read the
// environment directly, that knob would be invisible to the generated docs and
// could silently drift — exactly the class of bug that left
// GATEWAY_POSTGRES_CONN_TIMEOUT_MS dead (read in a since-deleted env-reader
// that the composition root never called). This test makes the boundary an
// enforced invariant rather than a convention.
//
// It is a plain `go test` (no build tag) so it runs in the default
// `go test ./...` set and in the dedicated arch CI job.
package arch_test

import (
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"regexp"
	"runtime"
	"sort"
	"strconv"
	"strings"
	"testing"
)

// shippedRoots are the top-level package trees that ship in the binary / public
// library surface and must therefore obey the config boundary. Test files
// (_test.go) are exempt everywhere — a test harness may read its own
// environment (e.g. GATEWAY_TEST_POSTGRES_DSN).
var shippedRoots = []string{"cmd", "internal", "pkg", "identityserver"}

// exemptDirs are directories under a shipped root that are excluded from the
// boundary, each for a specific, justified reason. Paths are slash-separated
// and relative to the repo root.
//
// Keep this list tiny. After centralizing every env read in internal/config it
// holds only the two unavoidable exemptions: the boundary itself, and the docs
// generator that PARSES config.go's source (so it legitimately contains
// GATEWAY_* tokens as data, and never reads the environment).
var exemptDirs = map[string]string{
	"internal/config": "the config boundary itself — the one place env reads are allowed",
	"cmd/docsgen":     "parses internal/config source as data (GATEWAY_* tokens are inputs, not env reads)",
}

// envReadFuncs are the os functions that read process environment. A shipped
// package calling any of these has bypassed the config boundary.
var envReadFuncs = map[string]bool{
	"Getenv":    true,
	"LookupEnv": true,
	"Environ":   true,
}

// bareEnvKeyRe matches a string literal that IS a GATEWAY_ environment-variable
// key (the whole value is the token). This is the shape of an env access —
// os.Getenv("GATEWAY_X") or any custom key-keyed lookup. It deliberately does
// NOT match prose that merely mentions a variable inside a sentence (operator
// hints / error messages like "set GATEWAY_X to enable ..."), which are
// legitimate outside config and are in fact relied on by cmd/docsgen to detect
// conditionally-required vars.
var bareEnvKeyRe = regexp.MustCompile(`^GATEWAY_[A-Z0-9_]+$`)

// repoRoot derives the repository root from this test file's location
// (tests/arch/config_boundary_test.go → three levels up), so the test is robust
// to how `go test` is invoked.
func repoRoot(t *testing.T) string {
	t.Helper()
	_, thisFile, _, ok := runtime.Caller(0)
	if !ok {
		t.Fatal("runtime.Caller failed; cannot locate repo root")
	}
	return filepath.Dir(filepath.Dir(filepath.Dir(thisFile)))
}

// isExempt reports whether a repo-root-relative directory is exempt (it equals
// or sits under an entry in exemptDirs).
func isExempt(relDir string) bool {
	relDir = filepath.ToSlash(relDir)
	for ex := range exemptDirs {
		if relDir == ex || strings.HasPrefix(relDir, ex+"/") {
			return true
		}
	}
	return false
}

func TestConfigBoundary(t *testing.T) {
	root := repoRoot(t)

	var violations []string
	scanned := 0

	for _, sr := range shippedRoots {
		base := filepath.Join(root, sr)
		if _, err := os.Stat(base); err != nil {
			t.Fatalf("expected shipped root %q to exist: %v", sr, err)
		}
		err := filepath.WalkDir(base, func(path string, d os.DirEntry, err error) error {
			if err != nil {
				return err
			}
			if d.IsDir() {
				rel, _ := filepath.Rel(root, path)
				if isExempt(rel) {
					return filepath.SkipDir
				}
				if d.Name() == "testdata" {
					return filepath.SkipDir
				}
				return nil
			}
			if !strings.HasSuffix(path, ".go") || strings.HasSuffix(path, "_test.go") {
				return nil
			}
			scanned++
			violations = append(violations, scanFile(t, root, path)...)
			return nil
		})
		if err != nil {
			t.Fatalf("walking %q: %v", sr, err)
		}
	}

	if scanned == 0 {
		t.Fatal("scanned zero shipped .go files; the walker is misconfigured")
	}

	if len(violations) > 0 {
		sort.Strings(violations)
		t.Errorf("config boundary: %d env-read leak(s) outside internal/config — "+
			"move the read into internal/config/config.go and inject the typed value:\n  - %s",
			len(violations), strings.Join(violations, "\n  - "))
	}
}

// scanFile parses one shipped Go file and returns a violation string (file:line)
// for every os.Getenv/os.LookupEnv/os.Environ call and every bare GATEWAY_ env-key
// string literal it contains.
func scanFile(t *testing.T, root, path string) []string {
	t.Helper()
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, path, nil, 0)
	if err != nil {
		t.Fatalf("parsing %s: %v", path, err)
	}
	rel, _ := filepath.Rel(root, path)
	rel = filepath.ToSlash(rel)

	var out []string
	ast.Inspect(file, func(n ast.Node) bool {
		switch node := n.(type) {
		case *ast.CallExpr:
			if sel, ok := node.Fun.(*ast.SelectorExpr); ok {
				if pkg, ok := sel.X.(*ast.Ident); ok && pkg.Name == "os" && envReadFuncs[sel.Sel.Name] {
					pos := fset.Position(node.Pos())
					out = append(out, rel+":"+strconv.Itoa(pos.Line)+": os."+sel.Sel.Name+
						" reads the environment outside internal/config")
				}
			}
		case *ast.BasicLit:
			if node.Kind != token.STRING {
				return true
			}
			val, err := strconv.Unquote(node.Value)
			if err != nil {
				return true
			}
			if bareEnvKeyRe.MatchString(val) {
				pos := fset.Position(node.Pos())
				out = append(out, rel+":"+strconv.Itoa(pos.Line)+": bare env-var key literal "+
					node.Value+" outside internal/config")
			}
		}
		return true
	})
	return out
}
