// Package connect provides the Connect-Go RPC handler layer for the identity
// service. It implements the identityconnect.IdentityServiceHandler interface
// generated by buf/protoc-gen-connect-go.
//
// The handler is a thin adapter — it extracts request metadata (IP, user agent,
// authenticated user ID), calls the appropriate service method, and converts
// service-layer domain types to proto response messages.
//
// Since buf generate has not run yet, the generated proto types
// (identitypb.*, identityconnect.*) do not exist. This code is written against
// the EXPECTED interface. The compiler will catch any mismatches when protos
// are generated.
//
// Expected generated import paths:
//
//	identitypb      "github.com/elloloop/identity/gen/go/identity/v1"
//	identityconnect "github.com/elloloop/identity/gen/go/identity/v1/identityv1connect"
package connect

import (
	"context"

	"github.com/elloloop/identity/internal/config"
	"github.com/elloloop/identity/internal/service"
	"github.com/elloloop/identity/pkg/assurance"
)

// IdentityHandler implements identityconnect.IdentityServiceHandler.
// Each method delegates to the appropriate service, translating between
// proto and service-layer types.
type IdentityHandler struct {
	auth    *service.AuthService
	admin   *service.AdminService
	groups  *service.GroupService
	help    *service.HelpService
	profile *service.ProfileService
	idv     *service.IdentityVerificationService
	domains *service.DomainService
	members *service.MembershipService
	// controlAdmin backs the control-plane admin RPCs (AdminCreateProject and
	// friends), authenticated by the shared admin secret rather than a user
	// JWT. nil on memory (no control plane) and when no secret is
	// configured — both disable the surface (CodeUnimplemented).
	controlAdmin *service.ControlPlaneAdminService
	captcha      assurance.Verifier
	cfg          *config.Config
}

// NewIdentityHandler creates a new IdentityHandler wired to the service
// layer. idv is optional: pass nil in deployments that do not need
// identity verification, and the IDV RPCs will return CodeUnimplemented.
//
// domains is optional: nil (memory, which has no control plane)
// causes the tenant-domain RPCs to return CodeUnimplemented.
//
// members is optional: nil (memory, which has no control plane)
// causes the tenant-membership/invitation RPCs to return CodeUnimplemented.
//
// controlAdmin is optional: nil (memory, or no configured admin secret)
// causes the control-plane admin RPCs to return CodeUnimplemented.
//
// captchaVerifier is optional: a nil verifier is treated as disabled, so
// the CAPTCHA gate behaves as a no-op regardless of the per-endpoint
// toggles. Production wiring passes a concrete verifier (or the no-op one)
// built from config.
func NewIdentityHandler(
	auth *service.AuthService,
	admin *service.AdminService,
	groups *service.GroupService,
	help *service.HelpService,
	profile *service.ProfileService,
	idv *service.IdentityVerificationService,
	domains *service.DomainService,
	members *service.MembershipService,
	controlAdmin *service.ControlPlaneAdminService,
	captchaVerifier assurance.Verifier,
	cfg *config.Config,
) *IdentityHandler {
	return &IdentityHandler{
		auth:         auth,
		admin:        admin,
		groups:       groups,
		help:         help,
		profile:      profile,
		idv:          idv,
		domains:      domains,
		members:      members,
		controlAdmin: controlAdmin,
		captcha:      captchaVerifier,
		cfg:          cfg,
	}
}

// checkCaptcha runs the CAPTCHA gate for an unauthenticated endpoint. It
// returns nil (skip) when CAPTCHA is globally disabled, the per-endpoint
// toggle is off, or no verifier is wired. Otherwise an empty token maps to
// ErrCaptchaRequired and a provider rejection maps to ErrCaptchaFailed —
// both surface to the client as CodePermissionDenied.
func (h *IdentityHandler) checkCaptcha(ctx context.Context, enforce bool, token, ip string) error {
	if h.cfg == nil || !h.cfg.CaptchaEnabled || !enforce || h.captcha == nil {
		return nil
	}
	if token == "" {
		return service.ErrCaptchaRequired
	}
	if err := h.captcha.Verify(ctx, token, ip); err != nil {
		return service.ErrCaptchaFailed
	}
	return nil
}

// The per-endpoint enforce accessors nil-check cfg so checkCaptcha's
// short-circuit (cfg == nil) is reachable without a panic when a test
// constructs a handler without a config.
func (h *IdentityHandler) captchaEnforcePasswordSignup() bool {
	return h.cfg != nil && h.cfg.CaptchaEnforcePasswordSignup
}

func (h *IdentityHandler) captchaEnforcePasswordLogin() bool {
	return h.cfg != nil && h.cfg.CaptchaEnforcePasswordLogin
}

func (h *IdentityHandler) captchaEnforcePasswordReset() bool {
	return h.cfg != nil && h.cfg.CaptchaEnforcePasswordReset
}

func (h *IdentityHandler) captchaEnforceEmailLoginCode() bool {
	return h.cfg != nil && h.cfg.CaptchaEnforceEmailLoginCode
}

func (h *IdentityHandler) captchaEnforceMagicLink() bool {
	return h.cfg != nil && h.cfg.CaptchaEnforceMagicLink
}

func (h *IdentityHandler) captchaEnforcePasskeySignup() bool {
	return h.cfg != nil && h.cfg.CaptchaEnforcePasskeySignup
}

// headerReader is a minimal interface satisfied by connect.Request (which
// embeds http.Header) — used to extract headers without depending on
// the concrete connect.Request type.
type headerReader interface {
	Get(string) string
}

// authenticatedUserID extracts the user ID injected by the auth middleware.
// The middleware sets X-Authenticated-User-Id after verifying the JWT.
func authenticatedUserID(headers headerReader) string {
	return headers.Get("X-Authenticated-User-Id")
}

// clientIP returns the client IP resolved by ClientIPMiddleware via the
// trusted-proxy allowlist. Direct reads of X-Forwarded-For are not
// trustworthy: anyone on the public internet can spoof that header.
func clientIP(headers headerReader) string {
	if ip := headers.Get("X-Client-IP"); ip != "" {
		return ip
	}
	// Fallbacks for tests / pre-middleware code paths.
	if ip := headers.Get("X-Forwarded-For"); ip != "" {
		return ip
	}
	return headers.Get("X-Real-Ip")
}

// clientUserAgent extracts the User-Agent header.
func clientUserAgent(headers headerReader) string {
	return headers.Get("User-Agent")
}
