// Package connect provides the Connect-Go RPC handler layer for the identity
// service. It implements the identityconnect.IdentityServiceHandler interface
// generated by buf/protoc-gen-connect-go.
//
// The handler is a thin adapter — it extracts request metadata (IP, user agent,
// authenticated user ID), calls the appropriate service method, and converts
// service-layer domain types to proto response messages.
//
// Since buf generate has not run yet, the generated proto types
// (identitypb.*, identityconnect.*) do not exist. This code is written against
// the EXPECTED interface. The compiler will catch any mismatches when protos
// are generated.
//
// Expected generated import paths:
//
//	identitypb      "github.com/elloloop/identity/gen/go/identity"
//	identityconnect "github.com/elloloop/identity/gen/go/identity/identityconnect"
package connect

import (
	"github.com/elloloop/identity/internal/config"
	"github.com/elloloop/identity/internal/service"
)

// IdentityHandler implements identityconnect.IdentityServiceHandler.
// Each method delegates to the appropriate service, translating between
// proto and service-layer types.
type IdentityHandler struct {
	auth    *service.AuthService
	admin   *service.AdminService
	groups  *service.GroupService
	help    *service.HelpService
	profile *service.ProfileService
	cfg     *config.Config
}

// NewIdentityHandler creates a new IdentityHandler wired to the service layer.
func NewIdentityHandler(
	auth *service.AuthService,
	admin *service.AdminService,
	groups *service.GroupService,
	help *service.HelpService,
	profile *service.ProfileService,
	cfg *config.Config,
) *IdentityHandler {
	return &IdentityHandler{
		auth:    auth,
		admin:   admin,
		groups:  groups,
		help:    help,
		profile: profile,
		cfg:     cfg,
	}
}

// headerReader is a minimal interface satisfied by connect.Request (which
// embeds http.Header) — used to extract headers without depending on
// the concrete connect.Request type.
type headerReader interface {
	Get(string) string
}

// authenticatedUserID extracts the user ID injected by the auth middleware.
// The middleware sets X-Authenticated-User-Id after verifying the JWT.
func authenticatedUserID(headers headerReader) string {
	return headers.Get("X-Authenticated-User-Id")
}

// clientIP extracts the client IP from the X-Forwarded-For header, falling
// back to X-Real-Ip.
func clientIP(headers headerReader) string {
	if ip := headers.Get("X-Forwarded-For"); ip != "" {
		return ip
	}
	return headers.Get("X-Real-Ip")
}

// clientUserAgent extracts the User-Agent header.
func clientUserAgent(headers headerReader) string {
	return headers.Get("User-Agent")
}
